### ISSUE TITLE
Add inline support

### ISSUE THREAD

**Issue by SpikedKira** [softlayer/sl-ember-components#1156] opened 2015-11-11 19:28 UTC
#sl-checkbox
#style
#v0.11.0

see sl-radio and bootstrap docs

**Comment by notmessenger** [comment] 2015-11-11 19:29
@SpikedKira Is this a duplicate of https://github.com/softlayer/sl-ember-components/issues/1148 or something different?

**Comment by SpikedKira** [comment] 2015-11-11 19:36
1148 applies to radio, this is for checkbox, the functionality is plainly missing.  radio had the functionality but needed a small fix.

**Comment by SpikedKira** [comment] 2015-11-12 17:08
um, there's a PR for this, not sure why it didn't auto-link

**Comment by SpikedKira** [comment] 2015-11-12 19:05
https://reviewable.io/reviews/softlayer/sl-ember-components/1162

**Closed** 2015-11-17 20:05 UTC
Labels: sl-checkbox, style
