### ISSUE TITLE
sl-select body is not aligned when page has scrollbar

### ISSUE THREAD

**Issue by alxyuu** [softlayer/sl-ember-components#422] opened 2015-07-14 22:16 UTC
When the body has sufficient height and there is a scrollbar on the page, opening a sl-select component will cause the scrollbar to be hidden and the entire page shifts over (except the select2 body). This causes the select2 body to be misaligned and produces unnecessary strain in the user due to the page shifting

**Comment by notmessenger** [comment] 2015-07-15 16:58
Duplicate of https://github.com/softlayer/sl-ember-components/issues/389

**Closed by notmessenger** 2015-07-15 16:58 UTC
Labels: duplicate
