### ISSUE TITLE
sl-chart not display correctly when browser window is contracted

### ISSUE THREAD

**Issue by azizpunjani** [softlayer/sl-ember-components#1242] opened 2015-12-07 14:02 UTC
![image](https://cloud.githubusercontent.com/assets/156746/11628666/c063b828-9cb8-11e5-9213-9ed92fe99eef.png)

**Comment by notmessenger** [comment] 2015-12-07 15:17
Duplicate of https://github.com/softlayer/sl-ember-components/issues/11

**Closed by notmessenger** 2015-12-07 15:17 UTC
