### ISSUE TITLE
sl-select doesn't support dynamically removing items from content

### ISSUE THREAD

**Issue by Samsinite** [softlayer/sl-ember-components#143] opened 2014-12-21 02:00 UTC
If the selected item is dynamically removed from the array bound to content, than the sl-select component becomes unusable and acts as if it is disabled. Dynamically adding items to the array that is bound to content works fine.

**Comment by alxyuu** [comment] 2015-07-20 20:01
@Samsinite I'm unable to reproduce the disabled part of the issue. When removing an element from content, the selector still works, although it is now selecting an element that does not exist.

**Comment by Samsinite** [comment] 2015-07-20 20:26
@alxyuu this was from whatever version was latest on Dec 2014. I've since stopped using sl-ember-components so I am unsure if this issue still exists.

**Comment by notmessenger** [comment] 2015-07-22 01:32
@Samsinite If you would not mind sharing, what is the reason you stopped using sl-ember-components?  If it is something we can change we would be interested in the information so that we can make modifications in the repository moving forward.  Thank you.

**Comment by Samsinite** [comment] 2015-07-23 21:04
Sure. I've outlined the main reasons below, some of which may be resolved by now.

 - Way too many components that I didn't regularly need or use.
 - Had too many issues with the select components using array promises and/or dynamically changing selection choices.
 - The bootstrap form components didn't seem to easily support [form columns](http://getbootstrap.com/css/#forms-horizontal).
 - Some of the components required us to import all of the styling, thus requiring us to use your custom bootstrap theme which didn't always play nice with other bootstrap plugins outside of your library.

Overall, you guys built some impressive tools, it just seemed -- at the time at least -- more customized to your specific workflow and standards, which I can completely understand. Our company tends to do the same thing, and make libraries more generalized as they mature.

**Comment by notmessenger** [comment] 2015-07-24 14:00
@alxyuu As you are unable to reproduce this I am going to close the issue.  Regarding the selection of a non-existent elemet, my recommendation normally would be to reset the selection to nothing or the label, but since we are going to be refactoring this entire component shortly, no such effort needs to/will be spent at this time.

**Closed by notmessenger** 2015-07-24 14:00 UTC
Labels: 2 - Working, bug, sl-select
